version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taskflow_api
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped
    networks:
      - taskflow_network

networks:
  taskflow_network:
    driver: bridge
